apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Infra-practice-isaac
  region: us-west-2

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

managedNodeGroups:
- name: infra-practice-nodes
  desiredCapacity: 2 
  instanceType: t2.micro
  ssh:
    enableSsm: true

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

secretsEncryption:
  # KMS key used for envelope encryption of Kubernetes secrets
  keyARN: arn:aws:kms:us-west-2:362231138751:key/bd27521d-e47e-48bc-83ba-a88263c8cd2d
